// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVFPhVbtistcfo7A2s6bUgVH1QOUGvqXQ',
    appId: '1:326913644158:web:66df69c6a8ff1f0246aa2f',
    messagingSenderId: '326913644158',
    projectId: 'resq-ai-5a8f7',
    authDomain: 'resq-ai-5a8f7.firebaseapp.com',
    storageBucket: 'resq-ai-5a8f7.firebasestorage.app',
    measurementId: 'G-R45RV64V5H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZQm_Loi4kcDYldC3MsbUqf5btESBrmhc',
    appId: '1:326913644158:android:d02ba44c15450ace46aa2f',
    messagingSenderId: '326913644158',
    projectId: 'resq-ai-5a8f7',
    storageBucket: 'resq-ai-5a8f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPUYVuNIiETjXpxg79lwn7DFtNOTPihCk',
    appId: '1:326913644158:ios:28513e8acbc483a646aa2f',
    messagingSenderId: '326913644158',
    projectId: 'resq-ai-5a8f7',
    storageBucket: 'resq-ai-5a8f7.firebasestorage.app',
    iosBundleId: 'com.resqai.resqAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPUYVuNIiETjXpxg79lwn7DFtNOTPihCk',
    appId: '1:326913644158:ios:28513e8acbc483a646aa2f',
    messagingSenderId: '326913644158',
    projectId: 'resq-ai-5a8f7',
    storageBucket: 'resq-ai-5a8f7.firebasestorage.app',
    iosBundleId: 'com.resqai.resqAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVFPhVbtistcfo7A2s6bUgVH1QOUGvqXQ',
    appId: '1:326913644158:web:ebc0ba9250c5e28c46aa2f',
    messagingSenderId: '326913644158',
    projectId: 'resq-ai-5a8f7',
    authDomain: 'resq-ai-5a8f7.firebaseapp.com',
    storageBucket: 'resq-ai-5a8f7.firebasestorage.app',
    measurementId: 'G-ZSNJZ10HC2',
  );
}
